version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: nexusdb
      POSTGRES_USER: nexususer
      POSTGRES_PASSWORD: nexuspw
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    command: npm start
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://nexususer:nexuspw@db:5432/nexusdb
      JWT_SECRET: your_jwt_secret_here
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  postgres_data: 